### ISSUE TITLE
After selecting the dark theme, some words can not see

### ISSUE THREAD

**Issue by maikebing** [tom-englert/Wax#20] opened 2017-01-05 16:03 UTC
![color](https://cloud.githubusercontent.com/assets/3445167/21687269/90b4a40c-d3a3-11e6-94ad-494da556b07a.PNG)

**Comment by Leogiciel** [comment] 2017-01-05 16:45
Already fixed with #17, will be delivered in next release.

**Comment by tom-englert** [comment] 2017-01-05 18:43
Duplicate of #17

**Closed by tom-englert** 2017-01-05 18:43 UTC
Labels: duplicate
