### ISSUE TITLE
Visual Studio 2022 install fails - Microsoft.VisualStudio.Component.CoreEdit missing

### ISSUE THREAD

**Issue by wilhelmmedetz** [tom-englert/Wax#77] opened 2021-11-29 14:24 UTC
Visual Studio 2022 installatiuon fails.
Eror message: Microsoft.VisualStudio.Component.CoreEdit missing

[dd_VSIXInstaller_20211129152053_7850.log](https://github.com/tom-englert/Wax/files/7618760/dd_VSIXInstaller_20211129152053_7850.log)

**Comment by DanielD** [comment] 2021-12-10 00:32
Same error here.

**Comment by tom-englert** [comment] 2021-12-10 07:36
Duplicate of #76

**Closed** 2021-12-10 14:19 UTC
Labels: duplicate
